name: Action Sample

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: execute echo command
        run: echo "Hello World!"
      - uses: actions/checkout@v1
      - run: cat sample.txt
      - run: cat sample.txt
